# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20c556ee8f5a867fb75dbf8026964290ed4f0a34ee975030efda1519c89ee0eccd4c3d5386a950280c60907a398a60832ebededafa0dad150d0d1519e8788f78

test:
  secret_key_base: 382b63e8ee892189f97fed7a8f6a874e41423a5a23914db753ca87b2664dda95c45a8df7902a30702e831987e7be3916467e674763549a7941b85f71eb22fb98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
